import torch
from torch import nn

from .base_path import BasePath
from .linear import LinearPath

class MLPpath(BasePath):
    """
    Neural-network path: linear base + learned correction.

    The configuration at time ``t`` is

    .. math::
        x(t) = x_\\text{base}(t) + (1 - t)\\, t \\cdot \\text{MLP}(2t - 1;\\, \\theta)

    Two design choices keep the path well-behaved:

    1. ``(1 - t) * t`` envelope pins both endpoints. Whatever the MLP
       outputs, the path equals the base path (reactant at ``t=0``,
       product at ``t=1``).
    2. MLP input is rescaled to ``t' = 2t - 1`` so the input domain is
       centered (``t' ∈ [-1, 1]``). At the midpath ``t=0.5``, the MLP
       pre-activation ``z = w·t' + b`` reduces to ``z = b`` (bias only),
       giving the smallest and most-Gaussian pre-activation distribution
       at the point of physical interest. This makes σ_min(J_path) at the
       saddle a clean, system-independent function of ``width`` (see the
       ``width`` parameter docstring).

    Parameters
    ----------
    width : int, default=128
        Hidden layer width ``M``. Default chosen so

        .. math::
            \\sigma_\\text{min}(J_\\text{path}, t=\\tfrac{1}{2}, \\text{fresh init}) \\approx 1

        which makes the standard threshold derivation
        ``thr_2 = δ · 2 · σ_min · fmax_target`` *system-independent*.
    depth : int, default=2
        Number of ``Linear`` layers (default: input + hidden + output).
    activation : str, default="gelu"
        Any nonlinearity in ``torch.nn`` (case-insensitive).
    base : BasePath, optional
        Base path the MLP corrects. Defaults to ``LinearPath``.
    """
    def __init__(
        self,
        width: int = 128,
        depth: int = 2,
        activation: str = "gelu",
        base: BasePath = None,
        **kwargs,
    ):
        super().__init__(**kwargs)

        activation_dict = {key.lower(): key for key in dir(nn) if not key.startswith('_')}
        name = activation_dict[activation.lower()]
        activation_class = getattr(nn, name)
        self.activation = activation_class()
        # Hidden width is `width` (default 128). System-independent.
        input_sizes = [1] + [width]*(depth - 1)
        output_sizes = input_sizes[1:] + [self.final_position.shape[-1]]
        self.layers = [
            nn.Linear(
                input_sizes[i//2], output_sizes[i//2], dtype=self.dtype, bias=True
            ) if i%2 == 0 else self.activation\
            for i in range(depth*2 - 1)
        ]
       
        self.mlp = nn.Sequential(*self.layers)
        self.mlp.to(self.device)
        self.neval = 0

        self.base = base if base is not None else LinearPath(**kwargs)
        
        print("Number of trainable parameters in MLP:", sum(p.numel() for p in self.parameters() if p.requires_grad))
        print(self.mlp)

    def get_positions(self, time: float):
        """
        Evaluate the path at ``time``.

        Parameters
        ----------
        time : torch.Tensor
            Times in [0, 1]; shape ``[N, 1]``.

        Returns
        -------
        torch.Tensor
            Positions of shape ``[N, D]``.
        """
        # (1 - time) * time pins the endpoints — at t=0 and t=1 the
        # learned correction vanishes so the path matches reactant /
        # product exactly regardless of MLP weights.
        # MLP input is rescaled to [-1, 1] (t' = 2t - 1) so pre-activations
        # at midpath come from bias only (z = b), giving a symmetric σ_min(t)
        # profile and a system-independent fresh-init σ_min calibration.
        mlp_out = self.mlp(2 * time - 1) * (1 - time) * time
        if self.fix_positions is not None:
            mlp_out[:, self.fix_positions] = 0.0
        base_out = self.base.get_positions(time)
        out = base_out + mlp_out
        return out

    def __get_positions(self, time: float):
        """
        Generates a geometric path using the MLP.

        Args:
            time (float): Time parameter for generating the path.
            *args: Additional arguments.

        Returns:
            torch.Tensor: The geometric path generated by the MLP.
        """
        # mlp_out = self.mlp(time) - (1 - time) * self.mlp(self.t_init) - time * self.mlp(self.t_final)
        # out = mlp_out
        mlp_out = self.mlp(time) * (1 - time) * time #* 4
        if self.fix_positions is not None:
            mlp_out[:, self.fix_positions.repeat_interleave(3)] = 0.0
        base_out = self.base.get_positions(time) #* (1 - (1 - time) * time * 4)
        out = base_out + mlp_out
        return out

# class ResNetLayer(nn.Module):
#     def __init__(
#         self,
#         output_size: int,
#         n_embed: int,
#         activation: str = "selu",
#     ):
#         super().__init__()
#         self.activation = activation_dict[activation]
#         self.layer = nn.Sequential(
#             nn.Linear(output_size, output_size * n_embed, dtype=torch.float64, bias=True),
#             self.activation,
#             nn.Linear(output_size * n_embed, output_size, dtype=torch.float64, bias=True),
#         )
#         # self.layer = SwiGLU(output_size, output_size)

#     def forward(self, x):
#         return x + self.layer(x)
    
# class SwiGLU(nn.Module):
#     def __init__(self, in_features, out_features):
#         super().__init__()
#         self.fc1 = nn.Linear(in_features, out_features)
#         self.fc2 = nn.Linear(in_features, out_features)
#         self.activation = nn.SiLU()

#     def forward(self, x):
#         return self.fc1(x) * self.activation(self.fc2(x))
