initialization_params:
  images: [[-0.558, 1.442], [0.623, 0.028]]
  path_params:
    name: mlp
    width: 128
    depth: 2
    activation: gelu
  track_loss: false
  track_ts: false
  num_record_points: 101
  device: cuda
  dtype: float32
  seed: 0
optimization_params:
  - potential_params:
      name: muller_brown
    integrator_params:
      path_integrand_names: pvre_pseudo_huber
      path_integrand_kwargs:
        pvre_pseudo_huber:
          delta: 0.05
      rtol: 0.5
      atol: 2.5e-3
    optimizer_params:
      optimizer:
        name: adam
        lr: 5.0e-3
      threshold: 5.0e-3
    num_optimizer_iterations: 1000
